services:
  db:
    image: mysql:9.1.0
    container_name: dvchevskii-blog-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - 33306:3306
    volumes:
      - type: bind
        source: ../scripts/mysql/initdb.d
        target: /docker-entrypoint-initdb.d
